// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQf1LL4F1t8cYtkJEkExqXB1KSaEF39zw',
    appId: '1:128254668963:web:d44f1a914a553740310f16',
    messagingSenderId: '128254668963',
    projectId: 'mini-chat-kpp-2025',
    authDomain: 'mini-chat-kpp-2025.firebaseapp.com',
    storageBucket: 'mini-chat-kpp-2025.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBtOa9SNo65eUA6TQcpB5Fs5ueqvQyg-V4',
    appId: '1:128254668963:android:bf214c59ceb82cc8310f16',
    messagingSenderId: '128254668963',
    projectId: 'mini-chat-kpp-2025',
    storageBucket: 'mini-chat-kpp-2025.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBrHdRMYjf_M6RGZ_gAnpONSY3cPL0DFQc',
    appId: '1:128254668963:ios:7be138c292d68944310f16',
    messagingSenderId: '128254668963',
    projectId: 'mini-chat-kpp-2025',
    storageBucket: 'mini-chat-kpp-2025.firebasestorage.app',
    iosBundleId: 'com.example.miniChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBrHdRMYjf_M6RGZ_gAnpONSY3cPL0DFQc',
    appId: '1:128254668963:ios:7be138c292d68944310f16',
    messagingSenderId: '128254668963',
    projectId: 'mini-chat-kpp-2025',
    storageBucket: 'mini-chat-kpp-2025.firebasestorage.app',
    iosBundleId: 'com.example.miniChat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDQf1LL4F1t8cYtkJEkExqXB1KSaEF39zw',
    appId: '1:128254668963:web:2e14af989a858afc310f16',
    messagingSenderId: '128254668963',
    projectId: 'mini-chat-kpp-2025',
    authDomain: 'mini-chat-kpp-2025.firebaseapp.com',
    storageBucket: 'mini-chat-kpp-2025.firebasestorage.app',
  );

}